config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  # this will fall through to ./views/application/robots.txt.erb, no need for an action method
  get 'robots.txt', to: "application#robots.txt", format: "text"

  # override sufia's about routing to use a static page instead of a content block
  get 'about', controller: 'static', action: 'about', as: 'about'
  # add a policy page
  get 'policy', controller: 'static', action: 'policy', as: 'policy'
  # override sufia's contact routing to use a static page instead of a form
  get 'contact', controller: 'static', action: 'contact', as: 'contact'
  # add a faq page
  get 'faq', controller: 'static', action: 'faq', as: 'faq'
  # remove help page, replaced with 'faq'
  get 'help', to: proc { raise ActionController::RoutingError.new('Not Found') }

  # remove weird zotero and mendeley pages with weird message, so it doesn't get
  # google indexed.
  get "zotero", to: proc { raise ActionController::RoutingError.new('Not Found') }
  get "mendeley", to: proc { raise ActionController::RoutingError.new('Not Found') }

  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  Hydra::BatchEdit.add_routes(self)
  mount Qa::Engine => '/authorities'

  # Administrative URLs
  namespace :admin do
    # Job monitoring
    constraints ResqueAdmin do
      mount Resque::Server, at: 'queues'
    end
  end

  mount Blacklight::Engine => '/'

    concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
    concerns :range_searchable

  end

  devise_for :users
  # https://github.com/plataformatec/devise/wiki/how-to:-change-the-default-sign_in-and-sign_out-routes
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end

  resources :welcome, only: 'index'
  root 'sufia/homepage#index'


  # Redirect from OLD work URLs to the new ones that we will install/override below.
  # Also we are getting rid of the `parent` URLs.
  get '/concern/generic_works/:id', to: redirect('/works/%{id}')
  get '/concern/generic_works/:id/viewer/:filesetid', to:  redirect('/works/%{id}/viewer/%{filesetid}')
  get '/concern/parent/:parent_id/generic_works/:id', to: redirect('/works/%{id}')
  get '/concern/parent/:parent_id/generic_works/:id/viewer/:filesetid', to: redirect('/works/%{id}/viewer/%{filesetid}')


  # Override collections/$id to point to our new custom controller
  get "collections/:id" => "collections_show#index", constraints: lambda { |req| req.params[:id] != "new" }
  get "collections/:id/range_limit" => "collections_show#range_limit"
  get "collections/:id/facet" => "collections_show#facet"
  get "focus/:id/range_limit" => "synthetic_category#range_limit"
  get "focus/:id/facet" => "synthetic_category#facet"


  curation_concerns_collections
  curation_concerns_basic_routes
  curation_concerns_embargo_management
  concern :exportable, Blacklight::Routes::Exportable.new


  #############
  #
  #  CHF crazy code to remove named route installed by sufia/CC, and install same named route
  #  with different URL. This is indeed confusing and weird, messing with trying to override
  #  already defined Rails resourceful routes and named helpers, which rails doesn't really want
  #  you to do.
  #
  ##############

    # Rails private API to _uninstall_ named route, may break in future
    Rails.application.routes.named_routes.send(:routes).delete(:curation_concerns_generic_work)
    Rails.application.routes.named_routes.send(:routes).delete(:curation_concerns_parent_generic_work)

    # Have to recreate the routes, such that they are at /works, not breaking any use of
    # curation_concerns_generic_work_path helper method.
    namespace :curation_concerns, path: '' do
      resources "generic_works", path: '/works', except: [:index]
    end

    # We want to GET RID of the `/concern/parent` urls, and just use standard /work urls.
    # This is a trick to create the `curation_concerns_parent_generic_work` route helper methods
    # sufia/CC use, to point to ur new desired /work URL. It depends on us having used private
    # Rails API to remove the previosu named route above.
    get "/works/:id", to: "curation_concerns/generic_works#show", params: {parent_id: nil}, as: "curation_concerns_parent_generic_work"


  # there might be a way to get curation_concerns routes to this for us,
  # but don't know it, and this is easy enough and works. Make the viewer
  # URL lead to ordinary show page, so JS can pick it up and launch viewer.
  get '/works/:id/viewer/:filesetid(.:format)' => 'curation_concerns/generic_works#show', as: :viewer
  get '/parent/:parent_id/works/:id/viewer/:filesetid(.:format)' => 'curation_concerns/generic_works#show'
  # our viewer json route
  get '/works/:id/viewer_images_info' => 'curation_concerns/generic_works#viewer_images_info', defaults: {format: "json"}, format: false, as: :viewer_images_info

  # redirect to signed s3
  get '/download_redirect/:id/:filename_key' => "downloads#s3_download_redirect", as: :s3_download_redirect

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end

  # local routes
  get '/opac_data/:rec_num', to: 'opac_data#load_bib'
  mount Hydra::RoleManagement::Engine => '/'

  get '/focus/:id', to: 'synthetic_category#index', as: :synthetic_category


  Hydra::BatchEdit.add_routes(self)
  # Sufia should be mounted before curation concerns to give priority to its routes
  mount Sufia::Engine => '/'
  mount CurationConcerns::Engine, at: '/'

end

app/models/collection.rb
# Generated by curation_concerns:models:install
class Collection < ActiveFedora::Base
  include ::CurationConcerns::CollectionBehavior
  # You can replace these metadata if they're not suitable
  include CurationConcerns::BasicMetadata

  # Set to a relative path _within_ our app/assets/images/collections
  property :representative_image_path, multiple: false, predicate: ::RDF::URI.new("http://chemheritage.org/ns/collection-thumb") do |index|
    index.as :displayable
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  include CurationConcerns::CollectionsControllerBehavior
  include Sufia::CollectionsControllerBehavior

  self.presenter_class = CHF::CollectionShowPresenter

  def form_class
    CollectionEditForm
  end

  def index
    documents = super
    @presenters = documents.
      map { |document| presenter_class.new(document, current_ability) }.
      sort! { |x,y| x.title.first <=> y.title.first }
  end
end

app/views/collections/_collection.html.erb
<%# This is a search result view

sufia 7.3's original was simply:

  <%= render partial: 'catalog/document', locals: { document: collection, document_counter: collection_counter }

We override to use CSS classes to match our localized
    app/views/curation_concerns/generic_works/_generic_work.html.erb

Didn't bother DRYing the template, just use common CSS classes %>

<%# This is a search result view %>

<%# sufia generated this:

  render 'catalog/document', document: generic_work, document_counter: generic_work_counter

# But we're taking it over to do what we want instead using simpler partials without
# so many layers of indirection.

# If we want to override only for certain list-view-types, may want to guard with
    document_index_view_type == :list
%>


<li id="document_<%= collection.to_param %>" class="chf-results-list-item document <%= render_document_class collection %>" itemscope itemtype="http://schema.org/Collection">
    <% doc_presenter = Chf::IndexPresenter.new(collection, self) %>

    <div class="chf-results-list-item-thumb">
      <%= link_to collection do %>
        <% image_tag CHF::CollectionShowPresenter.thumbnail_src(doc_presenter.solr_document), alt: "" %>
      <% end %>
      <%= doc_presenter.render_num_members %>
    </div>

    <div class="chf-results-list-item-content">

      <div class="chf-results-list-item-genre">
        <%= link_to "Collections", collections_path %>
      </div>


      <h2 class="chf-results-list-item-head brand-alt-h2" itemprop="name">
        <%= link_to collection.title_or_label, collection, itemprop: "url" %>

        <% if doc_presenter.needs_permission_badge? %>
          <small class="chf-results-list-item-permission"><%= doc_presenter.permission_badge %></small>
        <% end %>
      </h2>


      <% if doc_presenter.has_values_for?(Solrizer.solr_name("description", :stored_searchable)) %>
        <div class="chf-results-list-item-description">
          <% doc_presenter.description.each do |description| %>
            <%= format_description(description, truncate: true) %>
          <% end %>
        </div>
      <% end %>

    </div>
</li>

app/views/collections/_collection_teaser.html.erb
<%# Note this file could not be called simply _collection because that is used for search results %>
<div class="collection">
  <%= link_to collection_path(presenter.id) do %>
    <%= image_tag presenter.thumbnail_src, size: "266" %>
    <div class="collection-title-wrapper">
      <p class="collection-title"><%= presenter.title.first %></p>
    </div>
  <% end %>
</div>

app/views/collections/_form.html.erb
<%= simple_form_for @form, html: { class: 'editor' } do |f| %>
  <div id="descriptions_display">
    <h2 class="non lower"><%= t('sufia.collection.form.description') %></h2>
    <div id="base-terms">
      <% f.object.primary_terms.each do |term| %>
        <%= render_edit_field_partial(term, f: f) %>
      <% end %>
    </div>
    <%# chf edit: remove 'additional fields' button %>
  </div>
  <%= hidden_field_tag :type, params[:type] %>
  <% if params[:batch_document_ids].present? %>
    <% params[:batch_document_ids].each do |batch_item| %>
      <input type="hidden" name="batch_document_ids[]" value="<%= batch_item %>"/>
    <% end %>
  <% end %>

  <div class="collection_form_visibility">
    <%= render 'form_permission', f: f %>
  </div>

  <div class="primary-actions">
    <% if params[:action] == "new" %>
      <%= f.submit 'Create Collection', class: 'btn btn-primary', onclick: "confirmation_needed = false;", id: "create_submit", name: "create_collection" %>
    <% else %>
      <%= f.submit 'Update Collection', class: 'btn btn-primary', onclick: "confirmation_needed = false;", id: "update_submit", name: "update_collection" %>
    <% end %>
    <%= link_to t(:'helpers.action.cancel'), main_app.root_path, class: 'btn btn-link' %>
  </div>
<% end %>

app/views/collections/_media_display.html.erb
<%# overrideen from sufia to use our custom collection thumbnail instead
    of a font icon.
    https://github.com/projecthydra/sufia/blob/30fb2ad6f5402dbc541eb84c969ad4fa6dea1f3b/app/views/collections/_media_display.html.erb

    For now, we only do it if the presenter _has_ a thumbnail_src, don't totally
    understand why sometimes in admin screens it does not, different presenter
    I guess. Sufia!
%>

<% if presenter.respond_to?(:thumbnail_src) %>
  <div class="collection-show-media">
    <%= image_tag presenter.thumbnail_src %>
  </div>
<% else %>
  <%# original one from sufia %>
  <span class="<%= Sufia::ModelIcon.css_class_for(Collection) %> collection-icon-search"></span>
<% end %>

app/views/collections/index.html.erb
<div class="collections-index">
  <h1 class="collections-index-title brand-alt-h1">All Collections</h1>

  <div class="collections-index-list">
    <%= render partial: "collection_teaser", collection: @presenters, as: :presenter %>

    <%# hack to keep our last line of collection teasers left-aligned, assuming
        max four-columns %>
    <div class="collection-spacer"></div>
    <div class="collection-spacer"></div>
    <div class="collection-spacer"></div>
  </div>
</div>