config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  # this will fall through to ./views/application/robots.txt.erb, no need for an action method
  get 'robots.txt', to: "application#robots.txt", format: "text"

  # override sufia's about routing to use a static page instead of a content block
  get 'about', controller: 'static', action: 'about', as: 'about'
  # add a policy page
  get 'policy', controller: 'static', action: 'policy', as: 'policy'
  # override sufia's contact routing to use a static page instead of a form
  get 'contact', controller: 'static', action: 'contact', as: 'contact'
  # add a faq page
  get 'faq', controller: 'static', action: 'faq', as: 'faq'
  # remove help page, replaced with 'faq'
  get 'help', to: proc { raise ActionController::RoutingError.new('Not Found') }

  # remove weird zotero and mendeley pages with weird message, so it doesn't get
  # google indexed.
  get "zotero", to: proc { raise ActionController::RoutingError.new('Not Found') }
  get "mendeley", to: proc { raise ActionController::RoutingError.new('Not Found') }

  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  Hydra::BatchEdit.add_routes(self)
  mount Qa::Engine => '/authorities'

  # Administrative URLs
  namespace :admin do
    # Job monitoring
    constraints ResqueAdmin do
      mount Resque::Server, at: 'queues'
    end
  end

  mount Blacklight::Engine => '/'

    concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
    concerns :range_searchable

  end

  devise_for :users
  # https://github.com/plataformatec/devise/wiki/how-to:-change-the-default-sign_in-and-sign_out-routes
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end

  resources :welcome, only: 'index'
  root 'sufia/homepage#index'


  # Redirect from OLD work URLs to the new ones that we will install/override below.
  # Also we are getting rid of the `parent` URLs.
  get '/concern/generic_works/:id', to: redirect('/works/%{id}')
  get '/concern/generic_works/:id/viewer/:filesetid', to:  redirect('/works/%{id}/viewer/%{filesetid}')
  get '/concern/parent/:parent_id/generic_works/:id', to: redirect('/works/%{id}')
  get '/concern/parent/:parent_id/generic_works/:id/viewer/:filesetid', to: redirect('/works/%{id}/viewer/%{filesetid}')


  # Override collections/$id to point to our new custom controller
  get "collections/:id" => "collections_show#index", constraints: lambda { |req| req.params[:id] != "new" }
  get "collections/:id/range_limit" => "collections_show#range_limit"
  get "collections/:id/facet" => "collections_show#facet"
  get "focus/:id/range_limit" => "synthetic_category#range_limit"
  get "focus/:id/facet" => "synthetic_category#facet"


  curation_concerns_collections
  curation_concerns_basic_routes
  curation_concerns_embargo_management
  concern :exportable, Blacklight::Routes::Exportable.new


  #############
  #
  #  CHF crazy code to remove named route installed by sufia/CC, and install same named route
  #  with different URL. This is indeed confusing and weird, messing with trying to override
  #  already defined Rails resourceful routes and named helpers, which rails doesn't really want
  #  you to do.
  #
  ##############

    # Rails private API to _uninstall_ named route, may break in future
    Rails.application.routes.named_routes.send(:routes).delete(:curation_concerns_generic_work)
    Rails.application.routes.named_routes.send(:routes).delete(:curation_concerns_parent_generic_work)

    # Have to recreate the routes, such that they are at /works, not breaking any use of
    # curation_concerns_generic_work_path helper method.
    namespace :curation_concerns, path: '' do
      resources "generic_works", path: '/works', except: [:index]
    end

    # We want to GET RID of the `/concern/parent` urls, and just use standard /work urls.
    # This is a trick to create the `curation_concerns_parent_generic_work` route helper methods
    # sufia/CC use, to point to ur new desired /work URL. It depends on us having used private
    # Rails API to remove the previosu named route above.
    get "/works/:id", to: "curation_concerns/generic_works#show", params: {parent_id: nil}, as: "curation_concerns_parent_generic_work"


  # there might be a way to get curation_concerns routes to this for us,
  # but don't know it, and this is easy enough and works. Make the viewer
  # URL lead to ordinary show page, so JS can pick it up and launch viewer.
  get '/works/:id/viewer/:filesetid(.:format)' => 'curation_concerns/generic_works#show', as: :viewer
  get '/parent/:parent_id/works/:id/viewer/:filesetid(.:format)' => 'curation_concerns/generic_works#show'
  # our viewer json route
  get '/works/:id/viewer_images_info' => 'curation_concerns/generic_works#viewer_images_info', defaults: {format: "json"}, format: false, as: :viewer_images_info

  # redirect to signed s3
  get '/download_redirect/:id/:filename_key' => "downloads#s3_download_redirect", as: :s3_download_redirect

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end

  # local routes
  get '/opac_data/:rec_num', to: 'opac_data#load_bib'
  mount Hydra::RoleManagement::Engine => '/'

  get '/focus/:id', to: 'synthetic_category#index', as: :synthetic_category


  Hydra::BatchEdit.add_routes(self)
  # Sufia should be mounted before curation concerns to give priority to its routes
  mount Sufia::Engine => '/'
  mount CurationConcerns::Engine, at: '/'

end

app/models/search_builder/home_page.rb
class SearchBuilder

  # Restricts to only things a non-logged in user can see, but unlike the default
  # `Sufia::HomepageSearchBuilder` does _not_ restrict to just works, includes
  # anything that is visible in ordinary search results.
  class HomePage < SearchBuilder

    # Override to always return the null-user ability, no matter who is logged
    # in.
    def current_ability
      Ability.new(nil)
    end
  end
end

app/controllers/sufia/batch_uploads_controller.rb
class Sufia::BatchUploadsController < ApplicationController
  include Sufia::BatchUploadsControllerBehavior

  self.work_form_service = ::BatchUploadFormService
  self.curation_concern_type = work_form_service.form_class.model_class

end

app/controllers/sufia/homepage_controller_override.rb
Sufia::HomepageController.class_eval do
  # we don't actually want our local layout, cause it adds the search bar at the top
  # which we don't want. This is messy, yeah, not sure what this is doing honestly.
  layout 'sufia'


  # The default `Sufia::HomepageSearchBuilder` limits to just works. We actually
  # want everything that shows up in a normal search, but to limit to only public things,
  # to support our live count of items and have it match search results for public users.
  #
  # We override to a custom search builder to do that.
  def search_builder_class
    SearchBuilder::HomePage
  end

  protected

  def public_works_count
    @public_works_count ||= search_results({}).first.total
  end
  helper_method :public_works_count
end

app/helpers/sufia_helper.rb
module SufiaHelper
  include ::BlacklightHelper
  include Sufia::BlacklightOverride
  include Sufia::SufiaHelperBehavior
end

app/views/sufia/homepage/_category_teaser.html.erb
<div class="collection">
  <%= link_to synthetic_category_path(category.slug) do %>
    <%= image_tag category.thumb_asset_path, class: "category-image", size: "350" %>
    <div class="collection-title-wrapper">
      <p class="collection-title"><%= category.title.upcase %></p>
    </div>
  <% end %>
</div>

app/views/sufia/homepage/index.html.erb
<% content_for :page_title, application_name %>
<% content_for :container_class, "container-fluid homepage-content-wrapper branded-body-font" %>
<% provide :foo, "bar" %>
<% provide :suppress_controls, true %>

<div class="homepage-wrapper">

  <div class="row hero-search-container no-gutters">
    <figure class="hero-image col-xs-12 col-md-6">
      <%= image_tag "hero_image_2x.jpg", alt: "" %>
      <figcaption><%= hero_link('w6634363x') %></figcaptionw>
    </figure>
    <div class="col-xs-12 col-md-6 home-right-column">
      <div class="row search-container">
        <div class="digital-description col-xs-12 col-sm-6 col-md-12">
          <div class="pre-heading">Science History Institute</div>
          <h2 class="brand-alt-h2">Digital Collections</h2>
          <p>Search <%= number_with_delimiter(public_works_count) %> of our digitized items: artifacts, photographs, advertisements, letters, rare books, and more. You can also learn more about the rest of our <a href="https://sciencehistory.org/collections">collections.</a></p>
        </div>
        <div class="search-callouts col-xs-12 col-sm-6 col-md-12">
          <%= render 'catalog/search_form' %>
          <%# TODO: add 'public domain only' toggle %>
        </div>
      </div>
    </div>
  </div>

  <%# TODO: recent additions will go here %>

  <div class="row categories-list">
    <%= render partial: "category_teaser", collection: CHF::SyntheticCategory.all, as: :category %>
  </div>

  <div class="row featured-collection-container no-gutters">
    <div class="col-xs-12 col-sm-6">
      <div class="row featured-collection-callouts no-gutters">
        <div class="col-xs-12">
          <h2 class="brand-alt-h2">Featured Collection</h2>
          <p>The <%= link_to "Beckman Historical Collection", collection_path('wh246s128') %> covers the life and career of American scientist and philanthropist Dr. Arnold O. Beckman (1900–2004) and the growth of his companies. When Dr. Beckman invented the first commercially successful pH meter in 1934, he became a key player in both the American scientific instrument industry and the 20th-century scientific instrumentation revolution.</p>
          <%= link_to "Browse Collections",
            collections_path,
            class: "btn btn-emphasis btn-lg chf-callout-button" %>
        </div>
      </div>
    </div>
    <div class="featured-collection-image hidden-xs col-sm-6">
      <%= image_tag "featured_collection_narrow_2x.jpg", class: "hidden-md hidden-lg", alt: "" %>
      <%= image_tag "featured_collection_wide_2x.jpg", class: "hidden-xs hidden-sm", alt: "" %>
    </div>
  </div>

</div>